import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import com.menuorder.api.persistence.entity.User;
import com.menuorder.api.persistence.impl.UserServiceImpl;
import com.menuorder.api.persistence.service.UserService;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pranishres' at '10/24/16 4:05 PM' with Gradle 3.1
 *
 * @author pranishres, @date 10/24/16 4:05 PM
 */

public class LibraryTest {
	
    @Test public void saveUserTest() {
/*    	User user = new User();
    	user.setFirstName("Pranish");
    	user.setLastName("Shrestha");
    	user.setMiddleName("Maan");
    	user.setPassword("asdf");
    	user.setUsername("tetea");
    	
    	UserServiceImpl userServiceImpl = new UserServiceImpl();
    	userServiceImpl.saveOrUpdate(user);*/
    	
//    	assertTrue("saving user details to database", userService.saveOrUpdate(user));
    }
    
    @Test
    public void testAdd(){
    	String str = "hello";
    	System.out.println("testAdd()");
    	assertEquals("hello", str);
    }
}
